/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.learn.sso.customer;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
      //  String port = System.getProperty("server.port", "not-set");
       // System.out.println("server.port=" + port);
        System.out.println(new App().getGreeting());
    }
}
